version: '3'

networks:
  golang:

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080" # http
      - "443:443" # https
    networks:
      - golang
    depends_on:
      - db_private
    volumes:
      - ../../../../.:/go
  db_private:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: sistem_pendaftaran_merek
      MYSQL_USER: secret
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3306:3306'
    networks:
      - golang
    volumes:
      - ./mysql-entry-point.sql:/docker-entrypoint-initdb.d
      - private-db:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
# Names our volume
volumes:
  private-db: