version: '3'

networks:
  golang:

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080" # http
      - "443:443" # https
    networks:
      - golang
    depends_on:
      db_private:
        condition: service_healthy
    volumes:
      - ../../../../.:/go
      - ./assets/uploads/:/assets/uploads
  db_private:
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_DATABASE: sistem_pendaftaran_merek
      MYSQL_USER: secret
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    ports:
      - '3306:3306'
    networks:
      - golang
    volumes:
      - ./mysql-entry-point:/docker-entrypoint-initdb.d
      - ./private_db:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf